# Generated by Django 3.0.5 on 2020-04-14 19:31

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_product_pic.png', upload_to=auction.models.product_imagepath),
        ),
    ]
