# Generated by Django 3.0.5 on 2020-04-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_placed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
