# Generated by Django 3.0.5 on 2020-04-11 03:12

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20200410_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=auction.models.product_imagepath),
        ),
    ]
