# Generated by Django 3.0.4 on 2020-04-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.TextField(blank=True),
        ),
    ]
