# Generated by Django 3.0.5 on 2020-04-15 15:55

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20200415_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_pics/default_product_pic.png', upload_to=auction.models.product_imagepath),
        ),
    ]
